blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/GWUDCAP/cc-sessions#readme
    about: Check the documentation for guides and examples
  - name: Discussions
    url: https://github.com/GWUDCAP/cc-sessions/discussions
    about: Ask questions and discuss ideas with the community
