name: Feature Request
description: Suggest a new feature or enhancement for cc-sessions
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Have an idea for improving cc-sessions? Let us know!

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What kind of feature are you requesting?
      options:
        - New functionality
        - Enhancement to existing feature
        - Performance improvement
        - Documentation improvement
        - Developer experience improvement
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem/Motivation
      description: What problem does this feature solve? Why do you need it?
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples
    validations:
      required: false
